#!/bin/bash
#
# Copyright 2016, Sinclair R.F., Inc.

NAME=AXI_Stream_Slave

../../../../../ssbcc -q -P monitor_stack --display-opcode tb_${NAME}.9x8 || { echo "${NAME} compile failed" > /dev/stderr; exit 1; }
iverilog -o tb tb.v tb_${NAME}.v || { echo "${NAME} build failed" > /dev/stderr; exit 1; }
./tb > tb.out;

T="`md5sum -c md5sums --quiet`";
if [ -n "${T}" ]; then
  echo "${NAME} failed" > /dev/stderr;
  exit 1;
fi

echo "Passed:  ${NAME}";
exit 0;
