#!/bin/bash

../../../../ssbcc -q --display-opcode core.9x8 \
|| exit 1;

verilator --lint-only core.v

iverilog -o tb tb.v core.v \
|| exit 1;

if [ -n "`./tb | cmp - tb.good 2>&1`" ]; then
  echo "core trace differs from nominal output" > /dev/stderr;
  exit 1;
fi

echo "Passed:  core"
