#!/bin/bash

NAME="arch";

rm -f ssbcc;
ln -s ../../../../ssbcc;

# Test moving data into and out of the data stack and the return stack.
for MODE in nomem; do
  for ARCH in arch-${MODE}-*.9x8; do
    TEST="${NAME}/${ARCH}";
    cp ${ARCH} arch.9x8
    ./ssbcc -q arch.9x8 || { echo "ssbcc failed on ${TEST}"; exit 1; }
    verilator --lint-only arch.v || { echo "lint failed on ${TEST}"; exit 1;}
    iverilog -o tb tb.v arch.v || exit 1;
    if [ -n "`./tb | cmp - tb-${MODE}.good 2>&1`" ]; then
      echo "${TEST} failed" > /dev/stderr;
      exit 1;
    fi
    echo "Tested:  ${TEST}";
  done
done

# Test the high-order bits of the return stack for several PC widths and
# "COMBINE" configuration commands.
for ARCH in arch-calls-*.9x8; do
  SIZE="`echo ${ARCH} | sed -e 's/arch-calls-//' -e 's/[.-].*//'`";
  for (( ixcombine=0; ixcombine<4; ++ixcombine )); do
    TEST="${NAME}/${ARCH}@${ixcombine}";
    case ${ixcombine} in
      ( 0 ) sed -e "/@COMBINE@/d" ${ARCH} > arch.9x8;;
      ( 1 ) sed -e "s/@COMBINE@/COMBINE INSTRUCTION,DATA_STACK/" ${ARCH} > arch.9x8;;
      ( 2 ) sed -e "s/@COMBINE@/COMBINE INSTRUCTION,RETURN_STACK/" ${ARCH} > arch.9x8;;
      ( 3 ) sed -e "s/@COMBINE@/COMBINE RETURN_STACK,DATA_STACK/" ${ARCH} > arch.9x8;;
      ( * ) echo "Invalid value of ixcombine = ${ixcombine}" > /dev/stderr;
            exit 1;;
    esac
    ./ssbcc -q arch.9x8 || { echo "ssbcc failed on ${TEST}"; exit 1; }
    verilator --lint-only arch.v || { echo "lint failed on ${TEST}"; exit 1;}
    iverilog -o tb tb.v arch.v || exit 1;
    if [ -n "`./tb | cmp - "arch-calls-${SIZE}.good" 2>&1`" ]; then
      echo "${TEST} failed" > /dev/stderr;
      exit 1;
    fi
    echo "Tested:  ${TEST}";
  done
done

# Test memory writes and reads when there is one memory for several memory sizes
# and "COMBINE" configuration commands.
ARCH="arch-1mem";
for SIZE in 16 32 64 128 256; do
  for (( ixcombine=0; ixcombine<2; ++ixcombine )); do
    TEST="${NAME}/${ARCH}@${SIZE}.${ixcombine}";
    case ${ixcombine} in
      ( 0 ) sed -e "s/@CONFIG@/MEMORY RAM ram_a ${SIZE}/" ${ARCH}.9x8 > arch.9x8;;
      ( 1 ) sed -e "s/@CONFIG@/MEMORY RAM ram_a ${SIZE}\nCOMBINE ram_a/" ${ARCH}.9x8 > arch.9x8;;
      ( * ) echo "Invalid value of ixcombine = ${ixcombine}" > /dev/stderr;
            exit 1;;
    esac
    ./ssbcc -q arch.9x8 || { echo "ssbcc failed on ${TEST}"; exit 1; }
    verilator --lint-only arch.v || { echo "lint failed on ${TEST}"; exit 1;}
    iverilog -o tb tb.v arch.v || exit 1;
    if [ -n "`./tb | cmp - "${ARCH}-${SIZE}.good" 2>&1`" ]; then
      echo "${TEST} failed" > /dev/stderr;
      exit 1;
    fi
    echo "Tested:  ${TEST}";
  done
done

# Remove the temporary output files.
rm -f arch.9x8 arch.9x8-meta arch.v ssbcc tb;

# Print success message and return success indication.
echo "Passed:  ${NAME}";
exit 0;
